### ISSUE TITLE
Addon failing to launch

### ISSUE THREAD

**Issue by Lledor** [adxsoft/MapInsight-Addon#4]
I am running Freeplane version 1.8.6 on Linux Mint  20 Cinnamon, the MapInsight will not launch and I get this error  "java.lang.reflect.ReflectPermission" "suppressAccessChecks".

Is there a work-around for this problem?

**Comment by bepolymathe** [comment]
Any plan to make it works with 1.8 version ?

**Comment by adxsoft** [comment]
Hi

This was a bug in Freeplane 1.8. They provided me with a temporary fix
which works on 1.8. (see notes for Aug 13 2020 on github web page)

 I applied the fix to the MapInsight addon on github.

If you download the MapInsight addon from github again it should work with
1.8.

Download from https://github.com/adxsoft/MapInsight-Addon

Cheers
Allan

On Oct 17, 2020 at 08:39, bepolymathe <notifications@github.com> wrote:

Any plan to make it works with 1.8 version ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/adxsoft/MapInsight-Addon/issues/4#issuecomment-710665789>,
or unsubscribe

**Comment by bepolymathe** [comment]
Thanks @adxsoft for reply. 
You’re right. It works now.

**Comment by adxsoft** [comment]
Excellent .. hope you find Mapinsight add on useful.

Cheers
Allan


On Oct 19, 2020 at 06:42, bepolymathe <notifications@github.com> wrote:

Thanks @adxsoft <https://github.com/adxsoft> for reply.
You’re right. It works now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adxsoft/MapInsight-Addon/issues/4#issuecomment-711411683>,
or unsubscribe

**Comment by bepolymathe** [comment]
Hello, 

Thank you for this work. Its use will be essential in my research work. However, I have a problem with the "connectors manager" command which doesn't display any window. 
Moreover, the tooltip preview manages the theme in an unreadable way. An idea ?

![image](https://user-images.githubusercontent.com/29939805/96418198-adc41a00-11f2-11eb-9975-09edb523d71a.png)

**Comment by bepolymathe** [comment]
I have this in the log (if it’s help) :thinking: 

![image](https://user-images.githubusercontent.com/29939805/96421954-b66b1f00-11f7-11eb-80d5-0cb8f064d845.png)

**Comment by adxsoft** [comment]
Hi
I'll see what I can do.

I need some more information.

What computer you are using?
  -   Windows? Mac? Linux?
Which Operating System?
The Java version you are running

Can you also send any mindmap (.mm) file that you know has the problem.

Cheers
Allan

Can you send me your mindmap and I'll test it for you. What computer and
are you using?


On Oct 19, 2020 at 19:06, bepolymathe <notifications@github.com> wrote:

Hello,

Thank you for this work. Its use will be essential in my research work.
However, I have a problem with the "connectors manager" command which
doesn't display any window.
Moreover, the tooltip preview manages the theme in an unreadable way. An
idea ?

[image: image]
<https://user-images.githubusercontent.com/29939805/96418198-adc41a00-11f2-11eb-9975-09edb523d71a.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adxsoft/MapInsight-Addon/issues/4#issuecomment-711801007>,
or unsubscribe

**Comment by bepolymathe** [comment]
Hi, 

I’am running Freeplane 1.8.8 and java 1.8.0_265 on Fedora Linux (32 workstation) with Gnome 3.36 (Wayland). 

[CôteD’or.zip](https://github.com/adxsoft/MapInsight-Addon/files/5401373/CoteD.or.zip)

Here an example of a map. 

Thanks in advance for help.
Have a nice day.

**Comment by adxsoft** [comment]
Hi

I have been running tests and think that there is still a bug with Freeplane 1.8 running my MapInsight add on. I will follow this up with Freeplane support.

I have found however that if I can run MapInsight script successfully (including Connections Manager) from the Tools, Scripts menu

Here are the steps I took

A) CHANGE PLUGIN PREFERENCES
  1. Open Freeplane
  2. On Menu choose Freeplane -> Preferences -> Plugins tab
  3. Click on Permit Network Operations check box
  4. Close Preferences window
  5. Close Freeplane (so it remembers this preferences change)

B) LOAD THE MAPINSIGHT SCRIPT
  1. Open Freeplane again
  2. On Menu choose Tools -> Open User Directory
  3. Open the scripts folder
  4. Put the attached 'MapInsight_V1_2.groovy’ file into the scripts folder
  5. Close and then open Freeplane

C) RUN MAPINSIGHT FROM MENU
  1. On Menu choose Tools -> Scripts
  2. Click on ‘Map Insight_V1_2’


Regarding step A above I think that Freeplane 1.8 somehow requires network access for an addon. Not sure why but I will raise a support issue with them.

Thanks for pointing out the addon execution problem. Hopefully this will get you up and running

Cheers
Allan @ adxsoft

**Comment by adxsoft** [comment]
Oops .. here is the attachment I meant to attach!


Cheers
Allan @ adxsoft

**Comment by adxsoft** [comment]
Oops .. here is the attachment I meant to attach!
[MapInsight_V1_2.groovy.zip](https://github.com/adxsoft/MapInsight-Addon/files/5428962/MapInsight_V1_2.groovy.zip)

**Comment by adxsoft** [comment]
Forgot to say I tested out MapInsight_V1_2.groovy script with CôteD’or.mm and it was working correctly

**Comment by bepolymathe** [comment]
Hi @adxsoft 

Thanks for reply and patch it. It seems to work well ! 
I’am ready for explore connections in my documentation ! 
Have a good day.

**Comment by adxsoft** [comment]
Will retest the addon with Freeplane 1.9 when available

**Comment by bepolymathe** [comment]
> but the version posted in this thread actually works.

Yes indeed it works very well. I use it almost every day. But you're right it will be clearer from the home page

**Comment by adxsoft** [comment]
Good Suggestion. Link to latest version is now on the home page.

**Comment by euu2021** [comment]
I'm confused. In the homepage, you added a link to the homepage itself. I suggest linking to this https://github.com/adxsoft/MapInsight-Addon/issues/4#issuecomment-715262901 comment, which is the latest working version.
